In [1]:
import pandas as pd
import numpy as np

In [3]:
ch_df = pd.read_excel('Data_Source_Sheets/ChinaSocialMedia20200928.xlsx')

In [4]:
LANGS_COL = 'langs'
NAME_COL = 'name'
TYPE_COL = 'social_media_type'
HANDLE_COL = 'handle'

In [5]:
ch_extractions = {
    'embassy_twitter_handle': {
        'social_type': 'tw',
        'link_or_handle': 'handle',
        'account_col': 'Embassy Twitter handle',
        'lang_cols': [
            'Embassy Twitter language 1',
            'Embassy Twitter language 2',
            'Embassy Twitter language 3'
        ]
    },
    
    'chinese_ambassador_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Chinese Ambassador Twitter handle',
        'lang_cols': [
            'Chinese Ambassador Twitter language 1',
            'Chinese Ambassador Twitter language 2',
            'Chinese Ambassador Twitter language 3'
        ]
    },
    'chinese press_officer_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Chinese Press Officer Twitter handle',
        'lang_cols': [
            'Chinese Press Officer Twitter language 1'

        ]
    },
     'Deputy chief of mission Twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Deputy chief of mission Twitter handle',
        'lang_cols': []
    },
    
    'consul_general_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Consul General Twitter handle',
        'lang_cols': ['Consul General Twitter language 1']
    },
    'cg/mission_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'CG/Mission Twitter handle',
        'lang_cols': [
            'CG/Mission Twitter language 1',
            'CG/Mission Twitter language 2'
        ]
    },
    'twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Twitter handle',
        'lang_cols': [
            'Language 1',
            'Language 2'
        ]
    },
    
    'media_outlet_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Media outlet Twitter Handle',
        'lang_cols': [
            'Media outlet Twitter Language 1'
        ]
    },
    'institute_twitter_handle': {
        'social_type': 'tw',
        'handle_col': 'Institute Twitter handle',
        'lang_cols': []
    },
    
}

In [6]:
extractions = {
    'embassy twitter handle without NA': {
        'social_type': 'tw',
        'handle_col': 'Embassy Twitter handle without NA',
        'lang_cols': [
            'Embassy Twitter language 1',
            'Embassy Twitter language 2',
            'Embassy Twitter language 3'
        ]
    },
    
     'chinese ambassador twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Chinese Ambassador Twitter handle',
        'lang_cols': [
            'Chinese Ambassador Twitter language 1',
            'Chinese Ambassador Twitter language 2',
            'Chinese Ambassador Twitter language 3'
        ]
    },
    
    'chinese press officer twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Chinese Press Officer Twitter handle',
        'lang_cols': [
            'Chinese Press Officer Twitter language 1'

        ]
    },
    
    'deputy chief of mission twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Deputy chief of mission Twitter handle',
        'lang_cols': [
            'Chinese Deputy chief of mission Twitter language 1',
            'Chinese Deputy chief of mission Twitter language 2'
        ]
    },
    
    
    'main_facebook_page_link': {
        'social_type': 'fb',
        'handle_col': 'Main Facebook Page Link',
        'lang_cols': [
            'Language',
            'Language 2',
            'Language 3'
        ]
    },
    
    'consul general twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Consul General Twitter handle',
        'lang_cols': [
            'Consul General Twitter language 1'
        ]
    },
    
    'cg/mission twitter handle': {
        'social_type': 'tw',
        'handle_col': 'CG/Mission Twitter handle',
        'lang_cols': [
            'CG/Mission Twitter language 1',
            'CG/Mission Twitter language 2'
        ]
    },
    
    'consulate general facebook handle': {
        'social_type': 'fb',
        'handle_col': 'Consulate General Facebook handle',
        'lang_cols': [
            'Consulate General Facebook language 1'
        ]
    },
    
    'ministry official twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Ministry official Twitter handle',
        'lang_cols': [
            'Ministry official language 1',
            'Ministry official language 2'
        ]
    },
    
    'media outlet twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Media outlet Twitter handle',
        'lang_cols': [
            'Media outlet Twitter language 1'
        ]
    },
    
    'media outlet facebook handle': {
        'social_type': 'fb',
        'handle_col': 'Media outlet Facebook handle',
        'lang_cols': [
            'Media outlet Facebook language 1'
        ]
    },
    
    'Institute Twitter handle': {
        'social_type': 'tw',
        'handle_col': 'Institute Twitter handle',
        'lang_cols': [
            'Institute Twitter language 1'
        ]
    },
    
    'facebook link': {
        'social_type': 'fb',
        'handle_col': 'Facebook link',
        'lang_cols': [
            'Institute Facebook language 1',
            'Institute Facebook language 2'
        ]
    },
    
}

In [7]:
def extraction_func(df, social_type, handle_col, lang_cols):
    extracted_df = df[~df[handle_col].isna()].copy()
    extracted_df[LANGS_COL] = extracted_df[lang_cols].apply(lambda x: [lang for lang in x if lang != np.nan], axis=1)
    extracted_df[NAME_COL] = name
    extracted_df[TYPE_COL] = social_type
    extracted_df[HANDLE_COL] = extracted_df[handle_col]
    return extracted_df

In [8]:
extracted_dfs = []

for name, extract_params in extractions.items():
    extract_df = extraction_func(ch_df, **extract_params)
    extrextracted_dfsact_df[NAME_COL] = name
    .append(extract_df)

In [10]:
combined_fb_tw_handles = pd.concat(extracted_dfs)[[NAME_COL, TYPE_COL, HANDLE_COL, LANGS_COL]]

In [15]:
combined_fb_tw_handles['langs']

2       [English, Pashto, Persian]
10        [English, Albanian, nan]
22      [Portuguese, English, nan]
31         [Spanish, English, nan]
49          [English, German, nan]
                   ...
1197                    [nan, nan]
1201                    [nan, nan]
1206                    [nan, nan]
1211                    [nan, nan]
1213                    [nan, nan]
Name: langs, Length: 387, dtype: object

In [16]:
dfObj = pd.DataFrame(combined_fb_tw_handles, columns=['handle'])

In [17]:
pd.

                                                handle
2                                        ChinaEmbKabul
10                                       ChinaembassyT
22                                      ChinaEmbAngola
31                                         ChinaEmbArg
49                                     chinaembaustria
...                                                ...
1197  https://www.facebook.com/ConfuciusInstituteNJCU/
1201            https://www.facebook.com/savannahstate
1206          https://www.facebook.com/CIUNCCharlotte/
1211                   https://www.facebook.com/ciwky/
1213                 https://www.facebook.com/cccsdsu/

[387 rows x 1 columns]